### ISSUE TITLE
Use a GET link instead of a form POST for consent button

### ISSUE THREAD

**Issue by ftrotter** [ftrotter/batea_js#1]
Change the button on the options page to be a link with a GET variable set like this: 

https://batea.docgraph.org/consent/?token=abc123

**Comment by andrey-ivanov** [comment]
applied this logic. Uri for switching back to anonymous mode is not set still

**Comment by ftrotter** [comment]
To set the app back to anonymous mode, simply pass JSON of:

{"is_consented": false}

to the appropriate saveSetting API URL. 

I need to confirm that this works, before closing this bug.

**Comment by andrey-ivanov** [comment]
extension uses saveSetting to switch back to anonymous mode
