### ISSUE TITLE
Confirm that the basic browsing tracking functionality works

### ISSUE THREAD

**Issue by ftrotter** [ftrotter/batea_js#4]
Confirm that the basic browsing tracking functionality works

Search for term. no tracking. Visit clinical wikipedia page. Start tracking. hit back button. Still Track. go somewhere else. still tracking. Open a new blank tab (i.e. not just a link that opens in a new tab) stop tracking. 

Search for term. no tracking. Visit regex matching page. Start tracking. follow links. Still Track. go somewhere else. still tracking. Open a new blank tab (i.e. not just a link that opens in a new tab) stop tracking. 

This is the basic functionality that needs to be working...

-FT

**Comment by andrey-ivanov** [comment]
Checked. Both scenarios work for me taking into account referrer limitations I described earlier.
